import type { RecordingFormat } from "../helpers";
import type { ReliableVideoSupport } from "../export/offlineVideoEncode";

export type VideoFormatOption = { value: string; name?: string };
export type EnumOption = { value: string; name?: string };

export interface RecordingPanelProps {
  hasSourceVideo: boolean;
  sourceDuration: number;
  sourceTime: number;
  exporting: boolean;
  capturing: boolean;
  copySuccess: boolean;
  recordingTime: number;
  videoVolume: number;
  videoLoopMode: "realtime" | "offline" | "webcodecs";
  includeVideoAudio: boolean;
  reliableVideoSupport: ReliableVideoSupport | null;
  recordingFormats: RecordingFormat[];
  recFormatOptions: { options: EnumOption[] };
  activeRecFormatLabel: string;
  autoRecordFps: boolean;
  recordFps: number;
  reliableMaxFps: number;
  autoBitrate: boolean;
  bitrate: number;
  reliableSettleFrames: number;
  reliableStrictValidation: boolean;
  reliableScope: "loop" | "range";
  reliableRangeStart: number;
  reliableRangeEnd: number;
  videoDuration: number;
  recordedUrl: string | null;
  recordedBlob: Blob | null;
  progress: string | null;
  progressValue: number | null;
  onSetVideoLoopMode: (value: "offline" | "realtime" | "webcodecs") => void;
  onSetIncludeVideoAudio: (value: boolean) => void;
  onSetSelectedRecFormat: (value: string) => void;
  onSetAutoRecordFps: (value: boolean) => void;
  onSetRecordFps: (value: number) => void;
  onSetReliableMaxFps: (value: number) => void;
  onSetAutoBitrate: (value: boolean) => void;
  onSetBitrate: (value: number) => void;
  onSetReliableSettleFrames: (value: number) => void;
  onSetReliableStrictValidation: (value: boolean) => void;
  onSetReliableScope: (value: "loop" | "range") => void;
  onSetReliableRangeStart: (value: number) => void;
  onSetReliableRangeEnd: (value: number) => void;
  onRecord: () => void;
  onRecordLoop: () => void;
  videoPreviewRef: React.RefObject<HTMLVideoElement | null>;
  onSaveVideo: () => void;
  onCopyVideo: () => void | Promise<void>;
}

export interface FrameExportPanelProps {
  hasSourceVideo: boolean;
  exporting: boolean;
  copySuccess: boolean;
  videoFormat: string;
  frames: number;
  loopCaptureMode: "realtime" | "offline" | "webcodecs";
  loopAutoFps: boolean;
  gifFps: number;
  contactColumns: number;
  videoDuration: number;
  loopExportScope: "loop" | "range";
  loopRangeStart: number;
  loopRangeEnd: number;
  canUseGifFilterPalette: boolean;
  gifPaletteSource: "auto" | "filter";
  gifPalettePreview: number[][];
  gifPaletteOverflow: number;
  gifUrl: string | null;
  gifResultLabel: string | null;
  gifBlob: Blob | null;
  sequenceBlob: Blob | null;
  contactSheetBlob: Blob | null;
  contactSheetUrl: string | null;
  progress: string | null;
  progressValue: number | null;
  onSetFrames: (value: number) => void;
  onSetLoopCaptureMode: (value: "offline" | "realtime" | "webcodecs") => void;
  onSetLoopAutoFps: (value: boolean) => void;
  onSetGifFps: (value: number) => void;
  onSetContactColumns: (value: number) => void;
  onSetGifPaletteSource: (value: "filter" | "auto") => void;
  onSetLoopExportScope: (value: "loop" | "range") => void;
  onSetLoopRangeStart: (value: number) => void;
  onSetLoopRangeEnd: (value: number) => void;
  onAbortExport: () => void;
  onVideoExport: () => void;
  onSaveGif: () => void;
  onCopyGif: () => void | Promise<void>;
  onSaveSequence: () => void;
  onCopySequence: () => void | Promise<void>;
  onSaveContactSheet: () => void;
  onCopyContactSheet: () => void | Promise<void>;
}
