export const CHARSET = {
  MATRIX_FILM: "MATRIX_FILM",
  TERMINAL: "TERMINAL",
  HEX: "HEX",
  GLITCH: "GLITCH",
  MINIMAL: "MINIMAL",
  BLUEPRINT: "BLUEPRINT",
  TICKER: "TICKER",
  RUNES: "RUNES",
  CIRCUIT: "CIRCUIT",
  LEGAL: "LEGAL",
  TRANSIT: "TRANSIT",
  ALCHEMY: "ALCHEMY",
  WEATHER: "WEATHER",
  CYRILLIC: "CYRILLIC",
  JAPANESE: "JAPANESE",
  HIRAGANA: "HIRAGANA",
  CHINESE: "CHINESE",
  KANJI_LEDGER: "KANJI_LEDGER",
  COSMIC: "COSMIC",
  EMOJI: "EMOJI",
  BRAILLE: "BRAILLE",
  BOX_DRAWING: "BOX_DRAWING",
  BLOCK_ELEMENTS: "BLOCK_ELEMENTS",
  ARROWS: "ARROWS",
  MATH: "MATH",
  CURRENCY: "CURRENCY",
  ASCII_ART: "ASCII_ART",
  GREEK: "GREEK",
  MUSIC: "MUSIC",
  ASTROLOGY: "ASTROLOGY",
  OCR: "OCR",
  HAZARD: "HAZARD",
  CHESS: "CHESS",
  MAHJONG: "MAHJONG",
  PLAYING_CARDS: "PLAYING_CARDS",
  HEBREW: "HEBREW",
  ARABIC: "ARABIC",
  DEVANAGARI: "DEVANAGARI",
  MONGOLIAN: "MONGOLIAN",
  HIEROGLYPHS: "HIEROGLYPHS",
  STAR_MAP: "STAR_MAP",
  DNA_LAB: "DNA_LAB",
  PIXEL_DEBRIS: "PIXEL_DEBRIS",
  ANCIENT_NUMERALS: "ANCIENT_NUMERALS",
  CUNEIFORM: "CUNEIFORM",
  THAI: "THAI",
  BINARY_CONTROL: "BINARY_CONTROL",
  SUBWAY_SIGNAGE: "SUBWAY_SIGNAGE",
  SCHEMATICS: "SCHEMATICS",
  TAROT: "TAROT",
  DICE_TABLETOP: "DICE_TABLETOP",
  GLITCH_UI: "GLITCH_UI",
  TIBETAN: "TIBETAN",
  GEORGIAN: "GEORGIAN",
  ARMENIAN: "ARMENIAN",
  ETHIOPIC: "ETHIOPIC",
  CHEROKEE: "CHEROKEE",
  MORSE_SIGNAL: "MORSE_SIGNAL",
  MAP_SYMBOLS: "MAP_SYMBOLS",
  ALCHEMY_EXPANDED: "ALCHEMY_EXPANDED",
  DOMINOES: "DOMINOES",
  WEATHER_EXTENDED: "WEATHER_EXTENDED",
  UI_WIREFRAME: "UI_WIREFRAME",
  RAIL_TIMETABLE: "RAIL_TIMETABLE",
  BARCODE_SCANNER: "BARCODE_SCANNER",
  OGHAM: "OGHAM",
  TELETEXT: "TELETEXT",
  ORACLE_BONES: "ORACLE_BONES",
  INDUSTRIAL_STENCIL: "INDUSTRIAL_STENCIL",
  MANCHU: "MANCHU",
  SPACE_SIGNAL: "SPACE_SIGNAL",
  ALIEN_GLYPHS: "ALIEN_GLYPHS",
  YIJING: "YIJING",
  LEGACY_COMPUTING: "LEGACY_COMPUTING",
  TIFINAGH: "TIFINAGH",
  BYZANTINE_MUSIC: "BYZANTINE_MUSIC",
  MOJIBAKE: "MOJIBAKE",
  MOJIBAKE_UTF8_LATIN1: "MOJIBAKE_UTF8_LATIN1",
  MOJIBAKE_CP1252: "MOJIBAKE_CP1252",
  MOJIBAKE_REPLACEMENT: "MOJIBAKE_REPLACEMENT",
  MOJIBAKE_SHIFT_JIS: "MOJIBAKE_SHIFT_JIS",
  MOJIBAKE_HALF_WIDTH: "MOJIBAKE_HALF_WIDTH",
  MOJIBAKE_JP_UTF8: "MOJIBAKE_JP_UTF8",
  MOJIBAKE_DOUBLE_DECODE: "MOJIBAKE_DOUBLE_DECODE",
  MOJIBAKE_ENTITY_LEAK: "MOJIBAKE_ENTITY_LEAK",
  MOJIBAKE_FORUM_EXPORT: "MOJIBAKE_FORUM_EXPORT",
  MOJIBAKE_CONTROL_ROT: "MOJIBAKE_CONTROL_ROT",
  MOJIBAKE_CSV_EXCEL: "MOJIBAKE_CSV_EXCEL",
  MOJIBAKE_XML_SCREAM: "MOJIBAKE_XML_SCREAM",
  MOJIBAKE_SUBTITLE_RIP: "MOJIBAKE_SUBTITLE_RIP",
  MOJIBAKE_EMAIL_HEADER: "MOJIBAKE_EMAIL_HEADER",
  MOJIBAKE_PDF_COPY: "MOJIBAKE_PDF_COPY",
  MOJIBAKE_TERMINAL_BLEED: "MOJIBAKE_TERMINAL_BLEED",
  MOJIBAKE_ZALGO_EXPORT: "MOJIBAKE_ZALGO_EXPORT",
} as const;

export const CHARSET_MAP: Record<string, string> = {
  [CHARSET.MATRIX_FILM]: "ﾊﾐﾋｰｳｼﾅﾓﾆｻﾜﾂｵﾘｱﾎﾃﾏｹﾒｴｶｷﾑﾕﾗｾﾈｽﾀﾇﾍ012345789Z:.*+=¦日",
  [CHARSET.TERMINAL]: "$#%&@01[]{}<>/\\\\|=+*.-_:;~",
  [CHARSET.HEX]: "0123456789ABCDEF",
  [CHARSET.GLITCH]: "XZKRNVMW80B%#*@!?/\\\\|~^+-=",
  [CHARSET.MINIMAL]: ".:|!Il10",
  [CHARSET.BLUEPRINT]: "+-|/\\\\[]{}()<>#=:.0123456789",
  [CHARSET.TICKER]: "$%+-=?!0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  [CHARSET.RUNES]: "ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛇᛈᛉᛋᛏᛒᛖᛗ",
  [CHARSET.CIRCUIT]: "01<>[]{}()=+-_|/*#:&~",
  [CHARSET.LEGAL]: "§¶#%/\\()[]{}!?;:.,IVXLC0123456789",
  [CHARSET.TRANSIT]: "◉◎○●◇◆□■△▽▷◁|/\\\\+-=0123456789",
  [CHARSET.ALCHEMY]: "☉☿♀♁♂♃♄☽☾⚶⚷⚸⚹⚱✶✷✹",
  [CHARSET.WEATHER]: "☀☁☂☃☄⚡☼❄✺✹*.:~°",
  [CHARSET.CYRILLIC]: "ДЖИЙЛПФЦЧШЩЪЫЬЭЮЯБГЗКМНОРСТУХ0123456789",
  [CHARSET.JAPANESE]: "アイウエオカキクケコサシスセソタチツテトナニヌネノマミムメモヤユヨラリルレロワヲン",
  [CHARSET.HIRAGANA]: "あいうえおかきくけこさしすせそたちつてとなにぬねのまみむめもやゆよらりるれろわをん",
  [CHARSET.CHINESE]: "天地玄黄宇宙洪荒日月盈昃辰宿列张山川云雨雷电风火水木金土",
  [CHARSET.KANJI_LEDGER]: "金銀銅鉄円札株証取引利率勘定帳簿売買先物現物",
  [CHARSET.COSMIC]: "✦✧⋆✶✷✹✺✹☼☾☽⟁⌁⌘∞",
  [CHARSET.EMOJI]: "😀😎🤖👁️🌧️⚡🌙⭐🔥🫧🍄🛰️🧪🎲",
  [CHARSET.BRAILLE]: "⠁⠃⠇⠉⠋⠍⠛⠟⠿⡇⡏⡟⡿⣇⣧⣿",
  [CHARSET.BOX_DRAWING]: "┆┇┊┋│┃╽╿╎╏┼╋╬",
  [CHARSET.BLOCK_ELEMENTS]: "▁▂▃▄▅▆▇█▉▊▋▌▍▎▏",
  [CHARSET.ARROWS]: "↑↟↥↯→↠↦↗↓↡↧↺←↞↤↙↔↕⇄⇅",
  [CHARSET.MATH]: "∑∏∫∂∆∇∞≈≠≤≥∴∵⊕⊗⋄√",
  [CHARSET.CURRENCY]: "$¢£¤¥֏؋৲৳૱௹฿៛₠₡₿",
  [CHARSET.ASCII_ART]: " .'`^\",:;Il!i~+_-?][}{1)(|/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$",
  [CHARSET.GREEK]: "ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψω",
  [CHARSET.MUSIC]: "♩♪♫♬♭♮♯𝄞𝄢𝄡𝄽𝄾𝄿",
  [CHARSET.ASTROLOGY]: "☉☽☿♀♁♂♃♄♅♆♇♈♉♊♋♌♍♎♏♐♑♒♓",
  [CHARSET.OCR]: "OCRA0O1I7Z2S5B8G6DQUMWXHNVTPEFKLRYCJ",
  [CHARSET.HAZARD]: "☢☣⚠☠⚡⛔⛒☤⚕⌁",
  [CHARSET.CHESS]: "♔♕♖♗♘♙♚♛♜♝♞♟",
  [CHARSET.MAHJONG]: "🀇🀈🀉🀙🀚🀛🀐🀑🀒🀀🀁🀂🀃🀄🀅🀆",
  [CHARSET.PLAYING_CARDS]: "♠♡♢♣♤♥♦♧AJKQ10987",
  [CHARSET.HEBREW]: "אבגדהוזחטיכלמנסעפצקרשת",
  [CHARSET.ARABIC]: "ابتثجحخدذرزسشصضطظعغفقكلمنهوي",
  [CHARSET.DEVANAGARI]: "अआइईउऊएऐओऔकखगघचछजझटठडढतथदधनपफबभमयरलवशषसह",
  [CHARSET.MONGOLIAN]: "ᠠᠡᠢᠣᠤᠥᠦᠧᠨᠩᠪᠫᠬᠭᠮᠯᠰᠱᠲᠳᠴᠵᠶᠷ",
  [CHARSET.HIEROGLYPHS]: "𓀀𓀁𓀂𓀃𓀄𓀅𓁐𓁹𓂀𓂋𓃀𓃭𓄿𓅓𓆣𓇋𓇯𓈖𓉔𓊪𓋴𓌳",
  [CHARSET.STAR_MAP]: "☉☌☍☿♀♁♂♃♄♅♆♇✦✧⋆✶✷✹✺⟡◎◌⌖",
  [CHARSET.DNA_LAB]: "ACGT⟲⟴⧬⌬⚗⟡+-=:",
  [CHARSET.PIXEL_DEBRIS]: "░▒▓█▛▜▟▙▚▞▖▗▘▝▌▐",
  [CHARSET.ANCIENT_NUMERALS]: "ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫↀↁↂↇↈ",
  [CHARSET.CUNEIFORM]: "𒀀𒀁𒀂𒀸𒁹𒂍𒄑𒆠𒈠𒉌𒋗𒌋",
  [CHARSET.THAI]: "กขคงจฉชซญดตถทธนบปผพฟภมยรลวศษสห",
  [CHARSET.BINARY_CONTROL]: "01[]{}<>|/\\:-=+*#",
  [CHARSET.SUBWAY_SIGNAGE]: "ⓂⓈⓉⓁⒶⒷⒸ●○◎◉→←↑↓1234567890",
  [CHARSET.SCHEMATICS]: "⎍⎓⎔⌁⌂⏚⏦⏧⌬⎌⎇∿≈⊣⊢⊥",
  [CHARSET.TAROT]: "☉☾✦✧♃♄♅♆♇⚝⚚☽☿",
  [CHARSET.DICE_TABLETOP]: "⚀⚁⚂⚃⚄⚅✶✷✹✦✧⚔🛡",
  [CHARSET.GLITCH_UI]: "▣□▪▫◉◎⊞⊟☒☐⌫⌧⎋≡⋮⋯",
  [CHARSET.TIBETAN]: "ཀཁགངཅཆཇཉཏཐདནཔཕབམཙཚཛཝཞཟའཡརལཤསཧ",
  [CHARSET.GEORGIAN]: "აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ",
  [CHARSET.ARMENIAN]: "ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖ",
  [CHARSET.ETHIOPIC]: "ሀለሐመሠረሰሸቀበቨተቸኀነኘአከኸወዐዘዠየደጀገጠጨጰጸፀፈ",
  [CHARSET.CHEROKEE]: "ᎠᎡᎢᎣᎤᎥᎦᎧᎨᎩᎪᎫᎬᎭᎮᎯᎰᎱᎲᎳᎴᎵᎶᎷᎸᎹᎺᎻᎼ",
  [CHARSET.MORSE_SIGNAL]: ".-·-··--/|:;=+<>",
  [CHARSET.MAP_SYMBOLS]: "⌖⌘◎◉◌⟡⬠⬡▲△▼▽◀▶↟↡⌂",
  [CHARSET.ALCHEMY_EXPANDED]: "☉☿♀♁♂♃♄♅♆♇⚗⚱⚶⚷⚸⚹🜁🜂🜃🜄🜍🜔",
  [CHARSET.DOMINOES]: "🀱🀲🀳🀴🀵🀶🀷🀸🀹🀺🀻🀼🀽🀾🀿",
  [CHARSET.WEATHER_EXTENDED]: "☀☁☂☃☄⚡☼❄✺✹☾☽🌪🌫⛆⛇",
  [CHARSET.UI_WIREFRAME]: "┌┐└┘├┤┬┴┼▣□◫◧◨⊞⊟☐☒",
  [CHARSET.RAIL_TIMETABLE]: "⇄⇅⇆⇇⇈⇉↔↕➔➙➜●○◎1234567890",
  [CHARSET.BARCODE_SCANNER]: "|¦▌▐▍▎▊█#0123456789:-=",
  [CHARSET.OGHAM]: "ᚁᚂᚃᚄᚅᚆᚇᚈᚉᚊᚋᚌᚍᚎᚏᚐᚑᚒᚓᚔᚕᚖᚗᚘᚙᚚ",
  [CHARSET.TELETEXT]: "▘▝▖▗▀▄▌▐▚▞▛▜▟▙▒▓█",
  [CHARSET.ORACLE_BONES]: "𜼀𜼁𜼂𜼃𜼄𜼅𜼆𜼇𜼈𜼉𜼊𜼋𜼌𜼍",
  [CHARSET.INDUSTRIAL_STENCIL]: "AEFHKMPRSTXYZ0123456789/-+[]#",
  [CHARSET.MANCHU]: "ᠠᠡᠢᠣᠤᡝᡞᡟᠨᠩᠪᡦᡴᡤᠮᠯᠰᡧᡨᡩᠴᠵᠶᡵ",
  [CHARSET.SPACE_SIGNAL]: "✦✧⋆✶✷✹☼☾☽⟁⌖⌬◎◌⟡☄⛢⌁",
  [CHARSET.ALIEN_GLYPHS]: "⟟⌇⋔⍜⌖⟒⟁⊬⌬⟑⟊⋉☍⧖⟢⟡",
  [CHARSET.YIJING]: "䷀䷁䷂䷃䷄䷅䷆䷇䷈䷉䷊䷋䷌䷍䷎䷏",
  [CHARSET.LEGACY_COMPUTING]: "🬀🬁🬂🬃🬄🬅🬆🬇🬈🬉🬊🬋🬌🬍🬎🬏",
  [CHARSET.TIFINAGH]: "ⴰⴱⴳⴷⴹⴻⴼⴽⵀⵃⵅⵇⵉⵊⵍⵎⵏⵓⵔⵕⵖⵙⵚⵜⵡⵢⵣ",
  [CHARSET.BYZANTINE_MUSIC]: "𝀀𝀁𝀂𝀃𝀄𝀅𝀆𝀇𝀈𝀉𝀊𝀋𝀌𝀍𝀎𝀏",
  [CHARSET.MOJIBAKE]: "ÃÂ¢£¥¦¬¯°±²³µ¶·¸»¼½¿ÐÑØÞßæçðñøþÿ",
  [CHARSET.MOJIBAKE_UTF8_LATIN1]: "ÃÂâ€šâ€žâ€¦â€¡â€°â€¹â€™â€œâ€”â„¢Å“Å¡Å¸",
  [CHARSET.MOJIBAKE_CP1252]: "â€œâ€â€˜â€™â€”â€“â€¦Â©Â®Â°Â±Â·Â»Â¼Â½Â¾",
  [CHARSET.MOJIBAKE_REPLACEMENT]: "��?�□�ï¿½Ã�Â�â�",
  [CHARSET.MOJIBAKE_SHIFT_JIS]: "縺薙ｓ縺ｫ縺｡縺ｯ繧偵ｊ繧九〒繧後☆繧医％譁�蟄怜喧",
  [CHARSET.MOJIBAKE_HALF_WIDTH]: "ﾂｧﾂｲﾂｳﾂｪﾂｫｶﾞｷﾞｸﾞｹﾞｺﾞ｡｢｣､･ｰﾞﾟ",
  [CHARSET.MOJIBAKE_JP_UTF8]: "ãããããã«ã¿ã«ãæ¥æ¬èª",
  [CHARSET.MOJIBAKE_DOUBLE_DECODE]: "ÃÂ©ÃÂ£ÃÂ¼Ã¢â‚¬â„¢Ãâ€œÃÂ©ÃÂ±",
  [CHARSET.MOJIBAKE_ENTITY_LEAK]: "&amp;&lt;&gt;&quot;&#124;&#8212;&#x30A2;&#65533;",
  [CHARSET.MOJIBAKE_FORUM_EXPORT]: "ï½±ï½²ï½³Ã¢â‚¬â€â€¹â€œ�ﾂｹﾞ縺ｨ�□",
  [CHARSET.MOJIBAKE_CONTROL_ROT]: "�␀␁␂␃␄␇␈␍␟□⌫⍰�",
  [CHARSET.MOJIBAKE_CSV_EXCEL]: "ï»¿SEP=,Ã©Â£Å“;#DIV/0!#N/A#####",
  [CHARSET.MOJIBAKE_XML_SCREAM]: "&lt;tag&gt;&amp;#65533;&amp;amp;&quot;&lt;/tag&gt;",
  [CHARSET.MOJIBAKE_SUBTITLE_RIP]: "â™ªâ€¦ããï½¡ï½£[Music]�",
  [CHARSET.MOJIBAKE_EMAIL_HEADER]: "=?UTF-8?Q?Re=3A_=E6=97=A5=E6=9C=AC?=Ã¢â‚¬â€",
  [CHARSET.MOJIBAKE_PDF_COPY]: "ﬁﬂÃ—Â·□■···â€ƒâ€‹âˆ’",
  [CHARSET.MOJIBAKE_TERMINAL_BLEED]: "^[[31mÃ¢â€°Â¥Â±~$#@�",
  [CHARSET.MOJIBAKE_ZALGO_EXPORT]: "a̴̾͠Ã̵̿Â̶̈́�̷͠⍰̸͐□̴̑",
};

export const SHARED_CHARSET_GROUPS = [
  {
    label: "Featured",
    options: [
      { name: "Matrix film", value: CHARSET.MATRIX_FILM },
    ],
  },
  {
    label: "Languages & Scripts",
    options: [
      { name: "Japanese kana", value: CHARSET.JAPANESE },
      { name: "Hiragana stream", value: CHARSET.HIRAGANA },
      { name: "Chinese hanzi", value: CHARSET.CHINESE },
      { name: "Kanji ledger", value: CHARSET.KANJI_LEDGER },
      { name: "Cyrillic broadcast", value: CHARSET.CYRILLIC },
      { name: "Hebrew scroll", value: CHARSET.HEBREW },
      { name: "Arabic signal", value: CHARSET.ARABIC },
      { name: "Devanagari mantra", value: CHARSET.DEVANAGARI },
      { name: "Mongolian script", value: CHARSET.MONGOLIAN },
      { name: "Hieroglyphs", value: CHARSET.HIEROGLYPHS },
      { name: "Greek chorus", value: CHARSET.GREEK },
      { name: "Thai loops", value: CHARSET.THAI },
      { name: "Tibetan prayer flags", value: CHARSET.TIBETAN },
      { name: "Georgian script", value: CHARSET.GEORGIAN },
      { name: "Armenian manuscript", value: CHARSET.ARMENIAN },
      { name: "Ethiopic script", value: CHARSET.ETHIOPIC },
      { name: "Cherokee syllabary", value: CHARSET.CHEROKEE },
      { name: "Ogham stave", value: CHARSET.OGHAM },
      { name: "Oracle bones", value: CHARSET.ORACLE_BONES },
      { name: "Manchu script", value: CHARSET.MANCHU },
      { name: "Tifinagh", value: CHARSET.TIFINAGH },
    ],
  },
  {
    label: "Cinematic & Symbolic",
    options: [
      { name: "Glitch sigils", value: CHARSET.GLITCH },
      { name: "Cosmic dust", value: CHARSET.COSMIC },
      { name: "Space signal", value: CHARSET.SPACE_SIGNAL },
      { name: "Alien glyphs", value: CHARSET.ALIEN_GLYPHS },
      { name: "Emoji parade", value: CHARSET.EMOJI },
      { name: "Astrology chart", value: CHARSET.ASTROLOGY },
      { name: "Tarot spread", value: CHARSET.TAROT },
      { name: "Hazard tape", value: CHARSET.HAZARD },
      { name: "Star map", value: CHARSET.STAR_MAP },
      { name: "Alchemy expanded", value: CHARSET.ALCHEMY_EXPANDED },
      { name: "Weather extended", value: CHARSET.WEATHER_EXTENDED },
    ],
  },
  {
    label: "Technical",
    options: [
      { name: "Terminal static", value: CHARSET.TERMINAL },
      { name: "Hex dump", value: CHARSET.HEX },
      { name: "Blueprint markup", value: CHARSET.BLUEPRINT },
      { name: "Circuit traces", value: CHARSET.CIRCUIT },
      { name: "Transit map", value: CHARSET.TRANSIT },
      { name: "Weather radar", value: CHARSET.WEATHER },
      { name: "Box drawing", value: CHARSET.BOX_DRAWING },
      { name: "Block elements", value: CHARSET.BLOCK_ELEMENTS },
      { name: "Braille grid", value: CHARSET.BRAILLE },
      { name: "ASCII portrait", value: CHARSET.ASCII_ART },
      { name: "OCR scanline", value: CHARSET.OCR },
      { name: "Binary control room", value: CHARSET.BINARY_CONTROL },
      { name: "Subway signage", value: CHARSET.SUBWAY_SIGNAGE },
      { name: "Schematics", value: CHARSET.SCHEMATICS },
      { name: "Glitched UI", value: CHARSET.GLITCH_UI },
      { name: "UI wireframe", value: CHARSET.UI_WIREFRAME },
      { name: "Rail timetable", value: CHARSET.RAIL_TIMETABLE },
      { name: "Barcode scanner", value: CHARSET.BARCODE_SCANNER },
      { name: "Teletext mosaic", value: CHARSET.TELETEXT },
      { name: "Industrial stencil", value: CHARSET.INDUSTRIAL_STENCIL },
      { name: "Legacy computing", value: CHARSET.LEGACY_COMPUTING },
    ],
  },
  {
    label: "Mojibake & Corruption",
    options: [
      { name: "Mojibake spill", value: CHARSET.MOJIBAKE },
      { name: "UTF-8 as Latin-1", value: CHARSET.MOJIBAKE_UTF8_LATIN1 },
      { name: "CP1252 fallout", value: CHARSET.MOJIBAKE_CP1252 },
      { name: "Replacement soup", value: CHARSET.MOJIBAKE_REPLACEMENT },
      { name: "Shift-JIS wreckage", value: CHARSET.MOJIBAKE_SHIFT_JIS },
      { name: "Half-width panic", value: CHARSET.MOJIBAKE_HALF_WIDTH },
      { name: "JP UTF-8 spill", value: CHARSET.MOJIBAKE_JP_UTF8 },
      { name: "Double-decoded ruin", value: CHARSET.MOJIBAKE_DOUBLE_DECODE },
      { name: "Entity leak", value: CHARSET.MOJIBAKE_ENTITY_LEAK },
      { name: "Forum export hell", value: CHARSET.MOJIBAKE_FORUM_EXPORT },
      { name: "Control rot", value: CHARSET.MOJIBAKE_CONTROL_ROT },
      { name: "CSV in Excel ruin", value: CHARSET.MOJIBAKE_CSV_EXCEL },
      { name: "XML parser scream", value: CHARSET.MOJIBAKE_XML_SCREAM },
      { name: "Broken subtitle rip", value: CHARSET.MOJIBAKE_SUBTITLE_RIP },
      { name: "Email header poison", value: CHARSET.MOJIBAKE_EMAIL_HEADER },
      { name: "PDF copy rot", value: CHARSET.MOJIBAKE_PDF_COPY },
      { name: "Terminal bleed", value: CHARSET.MOJIBAKE_TERMINAL_BLEED },
      { name: "Zalgo export", value: CHARSET.MOJIBAKE_ZALGO_EXPORT },
    ],
  },
  {
    label: "Abstract & Encoded",
    options: [
      { name: "Minimal drizzle", value: CHARSET.MINIMAL },
      { name: "Ticker tape", value: CHARSET.TICKER },
      { name: "Rune storm", value: CHARSET.RUNES },
      { name: "Legal boilerplate", value: CHARSET.LEGAL },
      { name: "Alchemy table", value: CHARSET.ALCHEMY },
      { name: "Arrow storm", value: CHARSET.ARROWS },
      { name: "Math notebook", value: CHARSET.MATH },
      { name: "Currency board", value: CHARSET.CURRENCY },
      { name: "Music notation", value: CHARSET.MUSIC },
      { name: "DNA lab", value: CHARSET.DNA_LAB },
      { name: "Pixel debris", value: CHARSET.PIXEL_DEBRIS },
      { name: "Ancient numerals", value: CHARSET.ANCIENT_NUMERALS },
      { name: "Cuneiform shard", value: CHARSET.CUNEIFORM },
      { name: "Morse signal", value: CHARSET.MORSE_SIGNAL },
      { name: "Map symbols", value: CHARSET.MAP_SYMBOLS },
      { name: "Yijing hexagrams", value: CHARSET.YIJING },
      { name: "Byzantine musical", value: CHARSET.BYZANTINE_MUSIC },
    ],
  },
  {
    label: "Games & Glyphs",
    options: [
      { name: "Chess match", value: CHARSET.CHESS },
      { name: "Mahjong wall", value: CHARSET.MAHJONG },
      { name: "Playing cards", value: CHARSET.PLAYING_CARDS },
      { name: "Dice tabletop", value: CHARSET.DICE_TABLETOP },
      { name: "Domino rally", value: CHARSET.DOMINOES },
    ],
  },
] as const;

export const getCharsetString = (charset: string, fallback: string = CHARSET.MATRIX_FILM) =>
  CHARSET_MAP[charset] || CHARSET_MAP[fallback] || "";
