import { filterIndex, nearest } from "@gyng/ditherer-filters";
import {
  runCmykAngles,
  runHalftoneBackends,
  runLinearizeIsLive,
  runMedianCutBackendAgreement,
  runOrderedOklabPalette,
  runOrderedPaletteLevels,
  runQuantizePaletteSubset,
  runTriangleDitherSeed,
  runWorkerCrt,
  runWorkerSpecFilters,
} from "./contracts/core";
import {
  runAnaglyphCpuGlParity,
  runAlphaStatisticsHiddenRgb,
  runBayerGradientCorrection,
  runBayerNativeSamplePreservation,
  runBayerTemporalNoise,
  runBilateralBlurContracts,
  runCanvasOwnershipReuse,
  runCcdChargeAccumulation,
  runDigicamFlashContracts,
  runEinkDisplayContracts,
  runLaserSpeckleDiversity,
  runLegacyGpuStylizerContracts,
  runLcdEmitterTopology,
  runLcdLowAlphaEnergy,
  runLenticularNeutralAndAngle,
  runMoireLatticeControls,
  runMoireModeSeparation,
  runNightVisionSignalDependentNoise,
  runOscilloscopeSignalModes,
  runPainterlyStylizerContracts,
  runSpectrogramSharedMagnitude,
  runSpectrogramTinyNyquist,
  runStainedGlassColorModes,
  runScreenToneContracts,
  runJpegSubsamplingModes,
  runCoreToneEdgeContracts,
  runLegacyFieldContracts,
  runLegacyPrinterAndOutlineContracts,
  runLowAlphaStatisticsIsolation,
  runUltrasoundBoundaryEcho,
  runUpgradedAlphaPreservation,
  runVintageTvSignalContracts,
} from "./contracts/imaging";
import {
  runDaguerreotypeViewAngle,
  runDuplexPaperHighlights,
  runFilmGrainContinuousClusters,
  runFixedLayeredPrintFrameInvariance,
  runInfraredNeutrality,
  runLightLeakNeutrality,
  runNokiaLcdStates,
  runPaperTextureHighScaleBounded,
  runPhotocopierFrameInvariance,
  runPhotocopierToneContinuity,
  runPolaroidNoForcedBlur,
  runProjectionDustOcclusion,
  runProjectionScratchDiversity,
  runRisographNoForcedBleed,
  runScreenPrintHalftone,
  runStaticArtifactFrameInvariance,
  runSumiFiberCorrelation,
  runThermalNoiseContract,
  runThermalPrinterCellCoherence,
} from "./contracts/media";
import { runSdfInteriorDistance } from "./contracts/standards";
import {
  runPrintmakingAlphaPreservation,
  runPrintmakingToneMonotonic,
  runStippleDensityModulation,
} from "./contracts/printmaking";
import {
  runBloomLinearGlow,
  runBokehHighlightSpread,
  runCcdChargeLinearBloom,
  runColorGradientNoiseAlphaPreserved,
  runDespeckleEdgePreserved,
  runDespeckleImpulseRemoval,
  runFrequencyGaussianLowpass,
  runHalationLinearScreen,
  runLongExposureLinearAccumulation,
  runMotionBlurLinearStreak,
  runOrtonLinearGlow,
  runRadialBlurLinearAverage,
  runScanlineWarpAlphaWarped,
  runSharpenEdgeContrast,
  runTemporalColorCycleAlphaPreserved,
  runTiltShiftLinearDefocus,
  runVolumetricLightLinearShafts,
} from "./contracts/optical";
import { runAnalogStaticGhostAndAlpha } from "./contracts/glitch";
import {
  runStableFluidsNoProjectionRenders,
  runStableFluidsProjectionStable,
  runWakeMotionGated,
} from "./contracts/simulation";
import {
  runDodgeBurnDirectional,
  runHazeKoschmiederDepth,
  runSolarizeReversal,
} from "./contracts/tone";
import {
  runAnamorphicLinearRadial,
  runContourIsoLines,
  runStampEdgeBreakup,
  runWallpaperP2Rotation,
} from "./contracts/geometry";
import { runtimeFixtureIntegrity, runtimeOptions } from "./fixtures";
import { runEquivalent, runIdentity } from "./harness";
import type { ContractSuite } from "./contractRunner";
import type { Contract, FilterLike } from "./types";

const filterFor = (name: string): FilterLike => filterIndex[name] as FilterLike;
const defaultsFor = (name: string): Record<string, unknown> => filterFor(name).defaults ?? {};
const identityPalette = { ...nearest, options: { ...nearest.options, levels: 256 } };
const contract = (name: string, mode: string, run: Contract["run"]): Contract => ({ name, mode, run });

export const numericalContractSuites = (): ContractSuite[] => [
  {
    name: "pipeline-and-workers",
    contracts: [
      contract("rgbStripe", "worker", runWorkerCrt),
      contract("specification filters", "worker-and-temporal-state", runWorkerSpecFilters),
      contract("Ordered", "nearest-palette-levels", runOrderedPaletteLevels),
      contract("Ordered", "oklab-palette", runOrderedOklabPalette),
      contract("Quantize", "palette-subset", runQuantizePaletteSubset),
      contract("CMYK Halftone", "screen-angles", runCmykAngles),
      contract("Median Cut", "backend-agreement", runMedianCutBackendAgreement),
      contract("Triangle dither", "seeded-noise", runTriangleDitherSeed),
      contract("Halftone", "backend-liveness", runHalftoneBackends),
      contract("pipeline", "linearize-is-live", runLinearizeIsLive),
      contract("SDF Stylize", "nonzero-interior-distance", runSdfInteriorDistance),
      contract("upgraded physical imaging", "source-alpha-preservation", runUpgradedAlphaPreservation),
      contract("legacy GPU stylizers", "identity-alpha-tone-and-transparency", runLegacyGpuStylizerContracts),
      contract("painterly stylizers", "parity-alpha-sampling-and-modal-ties", runPainterlyStylizerContracts),
      contract("Bilateral Blur", "guided-parity-alpha-controls-and-tiny-rasters", runBilateralBlurContracts),
      contract("Bilateral Blur", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Bilateral Blur"),
        { ...defaultsFor("Bilateral Blur"), ...runtimeOptions() },
        {
          ...runtimeOptions(), sigmaSpatial: null, sigmaRange: Number.NaN,
          workingResolution: "INVALID",
        },
        2,
      )),
      contract("Bilateral Blur", "legacy-full-resolution-migration", () => runEquivalent(
        filterFor("Bilateral Blur"),
        { ...defaultsFor("Bilateral Blur"), ...runtimeOptions(), workingResolution: "FULL" },
        { ...runtimeOptions(), useDownsample: false },
        0,
      )),
      contract("Bilateral Blur", "legacy-quarter-resolution-migration", () => runEquivalent(
        filterFor("Bilateral Blur"),
        { ...defaultsFor("Bilateral Blur"), ...runtimeOptions(), workingResolution: "QUARTER" },
        { ...runtimeOptions(), downsampleFactor: 4 },
        0,
      )),
      contract("Bilateral Blur", "new-resolution-wins-over-legacy-state", () => runEquivalent(
        filterFor("Bilateral Blur"),
        { ...defaultsFor("Bilateral Blur"), ...runtimeOptions(), workingResolution: "QUARTER" },
        {
          ...defaultsFor("Bilateral Blur"), ...runtimeOptions(), workingResolution: "QUARTER",
          useDownsample: false, downsampleFactor: 1,
        },
        0,
      )),
      contract("Bilateral Blur", "legacy-separable-only-keeps-half-resolution", () => runEquivalent(
        filterFor("Bilateral Blur"),
        { ...defaultsFor("Bilateral Blur"), ...runtimeOptions(), workingResolution: "HALF" },
        { ...runtimeOptions(), useSeparableApproximation: false },
        0,
      )),
      contract("Pencil sketch", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Pencil Sketch"),
        { ...defaultsFor("Pencil Sketch"), ...runtimeOptions() },
        {
          ...runtimeOptions(), strokeDensity: null, contrast: Number.NaN,
          pencilColor: [null, null, null], paperColor: [null, null, null],
        },
        1,
      )),
      contract("Mosaic tile", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Mosaic Tile"),
        { ...defaultsFor("Mosaic Tile"), ...runtimeOptions() },
        {
          ...runtimeOptions(), tileSize: null, groutWidth: Number.POSITIVE_INFINITY,
          groutColor: [null, null, null], jitter: Number.NaN,
        },
        1,
      )),
      contract("Oil painting", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Oil Painting"),
        { ...defaultsFor("Oil Painting"), ...runtimeOptions() },
        { ...runtimeOptions(), radius: null, levels: Number.NaN },
        1,
      )),
      contract("Stained glass", "color-modes-and-alpha", runStainedGlassColorModes),
      contract("screen halftones", "tone-area-and-alpha", runScreenToneContracts),
      contract("JPEG Artifact", "subsampling-and-alpha", runJpegSubsamplingModes),
      contract("core tone and edge", "ordered-area-nms-and-clahe", runCoreToneEdgeContracts),
      contract("Posterize Dither", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Posterize Dither"),
        { ...defaultsFor("Posterize Dither"), ...runtimeOptions() },
        {
          ...runtimeOptions(), levelsR: null, levelsG: Number.POSITIVE_INFINITY,
          levelsB: Number.NaN, matrixSize: null,
        },
        0,
      )),
      contract("CMYK Halftone", "malformed-state-falls-back", () => runEquivalent(
        filterFor("CMYK Halftone"),
        { ...defaultsFor("CMYK Halftone"), ...runtimeOptions() },
        {
          ...runtimeOptions(), dotSize: null, angleC: null,
          angleM: Number.POSITIVE_INFINITY, angleY: Number.NaN, angleK: null,
          paperColor: [null, null, null],
        },
        0,
      )),
      contract("Edge Trace", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Edge Trace"),
        { ...defaultsFor("Edge Trace"), ...runtimeOptions() },
        {
          ...runtimeOptions(), threshold: null, lineWidth: Number.POSITIVE_INFINITY,
          lineColor: [null, null, null], renderMode: null, overlayMix: null,
          bgColor: [null, null, null],
        },
        0,
      )),
      contract("CLAHE", "sparse-state-falls-back", () => runEquivalent(
        filterFor("CLAHE"),
        { ...defaultsFor("CLAHE"), ...runtimeOptions(), tileSize: 8 },
        { ...runtimeOptions(), tileSize: 8 },
        1,
      )),
      contract("legacy scalar fields", "bands-convergence-and-alpha", runLegacyFieldContracts),
      contract("legacy printer and outline", "tone-density-and-alpha", runLegacyPrinterAndOutlineContracts),
      contract("Contour Lines", "sparse-state-falls-back", () => runEquivalent(
        filterFor("Contour Lines"),
        { ...defaultsFor("Contour Lines"), ...runtimeOptions(), levels: 5 },
        { ...runtimeOptions(), levels: 5 },
        0,
      )),
      contract("Anisotropic diffusion", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Anisotropic diffusion"),
        { ...defaultsFor("Anisotropic diffusion"), ...runtimeOptions() },
        {
          ...runtimeOptions(), iterations: Number.NaN, kappa: Number.POSITIVE_INFINITY,
          lambda: Number.NaN, conductance: "INVALID",
        },
        0,
      )),
      contract("Dot Matrix", "sparse-state-falls-back", () => runEquivalent(
        filterFor("Dot Matrix"),
        { ...defaultsFor("Dot Matrix"), ...runtimeOptions(), dotSize: 6 },
        { ...runtimeOptions(), dotSize: 6 },
        0,
      )),
      contract("Pixel Outline", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Pixel Outline"),
        { ...defaultsFor("Pixel Outline"), ...runtimeOptions() },
        {
          ...runtimeOptions(), outlineColor: [Number.NaN], outlineWidth: Number.NaN,
          mergeThreshold: Number.POSITIVE_INFINITY,
        },
        0,
      )),
    ],
  },
  {
    name: "display-and-capture",
    contracts: [
      contract("Night vision", "signal-dependent-shot-noise", runNightVisionSignalDependentNoise),
      contract("imaging alpha statistics", "hidden-rgb-invariance", runAlphaStatisticsHiddenRgb),
      contract("imaging alpha statistics", "low-alpha-isolation", runLowAlphaStatisticsIsolation),
      contract("Night vision", "sparse-direct-options-normalize-cpu", () => runEquivalent(
        filterFor("Night vision"),
        { ...defaultsFor("Night vision"), ...runtimeOptions(), gain: 5, _webglAcceleration: false },
        { ...runtimeOptions(), gain: 5, _webglAcceleration: false },
        0,
      )),
      contract("Night vision", "sparse-direct-options-normalize-gl", () => runEquivalent(
        filterFor("Night vision"),
        { ...defaultsFor("Night vision"), ...runtimeOptions(), gain: 5 },
        { ...runtimeOptions(), gain: 5 },
        0,
      )),
      contract("Night vision", "malformed-direct-options-normalize-cpu", () => runEquivalent(
        filterFor("Night vision"),
        { ...defaultsFor("Night vision"), ...runtimeOptions(), _webglAcceleration: false },
        {
          ...runtimeOptions(), _webglAcceleration: false, gain: Number.NaN,
          grain: Number.POSITIVE_INFINITY, bloomRadius: "wide", bloomStrength: null,
          vignette: Number.NEGATIVE_INFINITY, animSpeed: null, palette: null,
        },
        0,
      )),
      contract("Night vision", "malformed-direct-options-normalize-gl", () => runEquivalent(
        filterFor("Night vision"),
        { ...defaultsFor("Night vision"), ...runtimeOptions() },
        {
          ...runtimeOptions(), gain: Number.NaN, grain: Number.POSITIVE_INFINITY,
          bloomRadius: "wide", bloomStrength: null, vignette: Number.NEGATIVE_INFINITY,
          animSpeed: null, palette: null,
        },
        0,
      )),
      contract("Ultrasound", "impedance-boundary-response", runUltrasoundBoundaryEcho),
      contract("Ultrasound", "sparse-direct-options-normalize-cpu", () => runEquivalent(
        filterFor("Ultrasound"),
        { ...defaultsFor("Ultrasound"), ...runtimeOptions(), brightness: 2, _webglAcceleration: false },
        { ...runtimeOptions(), brightness: 2, _webglAcceleration: false },
        0,
      )),
      contract("Ultrasound", "sparse-direct-options-normalize-gl", () => runEquivalent(
        filterFor("Ultrasound"),
        { ...defaultsFor("Ultrasound"), ...runtimeOptions(), brightness: 2 },
        { ...runtimeOptions(), brightness: 2 },
        0,
      )),
      contract("Ultrasound", "malformed-direct-options-normalize-cpu", () => runEquivalent(
        filterFor("Ultrasound"),
        { ...defaultsFor("Ultrasound"), ...runtimeOptions(), _webglAcceleration: false },
        {
          ...runtimeOptions(), _webglAcceleration: false, fanAngle: Number.NaN,
          speckle: Number.POSITIVE_INFINITY, brightness: null, scanLines: "true",
          markers: 1, animSpeed: null, palette: null,
        },
        0,
      )),
      contract("Ultrasound", "malformed-direct-options-normalize-gl", () => runEquivalent(
        filterFor("Ultrasound"),
        { ...defaultsFor("Ultrasound"), ...runtimeOptions() },
        {
          ...runtimeOptions(), fanAngle: Number.NaN, speckle: Number.POSITIVE_INFINITY,
          brightness: null, scanLines: "true", markers: 1, animSpeed: null, palette: null,
        },
        0,
      )),
      contract("Mavica FD7", "sparse-direct-options-normalize-gl", () => runEquivalent(
        filterFor("Mavica FD7"),
        { ...defaultsFor("Mavica FD7"), ...runtimeOptions(), flash: true },
        { ...runtimeOptions(), flash: true },
        0,
      )),
      contract("Mavica FD7", "malformed-direct-options-normalize-gl", () => runEquivalent(
        filterFor("Mavica FD7"),
        { ...defaultsFor("Mavica FD7"), ...runtimeOptions() },
        {
          ...runtimeOptions(), captureMode: "INVALID", quality: null, sceneMode: 42,
          pictureEffect: "INVALID", lighting: false, flash: "false",
          flashPower: Number.NaN, flashFalloff: null, flashOffsetX: Number.POSITIVE_INFINITY,
          flashOffsetY: "up", smear: 1, nativeVgaOutput: "false", frameJitter: 2,
        },
        0,
      )),
      contract("Lenticular", "neutral-source-and-angle-selection", runLenticularNeutralAndAngle),
      contract("Lenticular", "sparse-direct-options-normalize", () => runEquivalent(
        filterFor("Lenticular"),
        { ...defaultsFor("Lenticular"), ...runtimeOptions(), viewAngle: 0.35 },
        { ...runtimeOptions(), viewAngle: 0.35 },
        0,
      )),
      contract("LCD Display", "emitter-topology", runLcdEmitterTopology),
      contract("LCD Display", "low-alpha-cell-energy", runLcdLowAlphaEnergy),
      contract("LCD Display", "sparse-direct-options-normalize", () => runEquivalent(
        filterFor("LCD Display"),
        { ...defaultsFor("LCD Display"), ...runtimeOptions(), brightness: 1.25 },
        { ...runtimeOptions(), brightness: 1.25 },
        0,
      )),
      contract("LCD Display", "malformed-direct-options-normalize", () => runEquivalent(
        filterFor("LCD Display"),
        { ...defaultsFor("LCD Display"), ...runtimeOptions() },
        {
          ...runtimeOptions(), pixelSize: Number.NaN, subpixelLayout: "INVALID",
          brightness: null, gapDarkness: Number.POSITIVE_INFINITY, palette: null,
        },
        0,
      )),
      contract("Spectrogram", "shared-magnitude-reference", runSpectrogramSharedMagnitude),
      contract("Spectrogram", "tiny-window-and-nyquist", runSpectrogramTinyNyquist),
      contract("Spectrogram", "sparse-direct-options-normalize", () => runEquivalent(
        filterFor("Spectrogram"),
        { ...defaultsFor("Spectrogram"), ...runtimeOptions(), logScale: false },
        { ...runtimeOptions(), logScale: false },
        0,
      )),
      contract("Spectrogram", "malformed-direct-options-normalize-cpu", () => runEquivalent(
        filterFor("Spectrogram"),
        { ...defaultsFor("Spectrogram"), ...runtimeOptions(), _webglAcceleration: false },
        {
          ...runtimeOptions(), _webglAcceleration: false, colormap: "INVALID",
          logScale: "true", freqBins: Number.NaN, dynamicRange: null, palette: null,
        },
        0,
      )),
      contract("Spectrogram", "malformed-direct-options-normalize-gl", () => runEquivalent(
        filterFor("Spectrogram"),
        { ...defaultsFor("Spectrogram"), ...runtimeOptions() },
        {
          ...runtimeOptions(), colormap: "INVALID", logScale: "true",
          freqBins: Number.NaN, dynamicRange: null, palette: null,
        },
        0,
      )),
      contract("Anaglyph", "cpu-gl-parity", runAnaglyphCpuGlParity),
      contract("Anaglyph", "sparse-direct-options-normalize", () => runEquivalent(
        filterFor("Anaglyph"),
        { ...defaultsFor("Anaglyph"), ...runtimeOptions(), strength: 18 },
        { ...runtimeOptions(), strength: 18 },
        0,
      )),
      contract("Bayer Sensor", "native-cfa-sample-preservation", runBayerNativeSamplePreservation),
      contract("Bayer Sensor", "temporal-noise-fixed-defects", runBayerTemporalNoise),
      contract("Bayer Sensor", "gradient-corrected-edge-reconstruction", runBayerGradientCorrection),
      contract("Bayer Sensor", "sparse-direct-options-normalize", () => runEquivalent(
        filterFor("Bayer Sensor"),
        { ...defaultsFor("Bayer Sensor"), ...runtimeOptions(), sensorNoise: 0.08 },
        { ...runtimeOptions(), sensorNoise: 0.08 },
        0,
      )),
      contract("Moiré / Aliasing", "mode-lattice-separation", runMoireModeSeparation),
      contract("Moiré / Aliasing", "angle-pitch-and-zero-drift", runMoireLatticeControls),
      contract("Moiré / Aliasing", "sparse-direct-options-normalize", () => runEquivalent(
        filterFor("Moiré / Aliasing"),
        { ...defaultsFor("Moiré / Aliasing"), ...runtimeOptions(), angle: 11 },
        { ...runtimeOptions(), angle: 11 },
        0,
      )),
      contract("Moiré / Aliasing", "zero-strength-identity", () => runIdentity(
        filterFor("Moiré / Aliasing"),
        { ...defaultsFor("Moiré / Aliasing"), ...runtimeOptions(), strength: 0 },
        0,
      )),
    ],
  },
  {
    name: "instruments-and-sensors",
    contracts: [
      contract("Oscilloscope", "signal-modes-and-cpu-gl-parity", runOscilloscopeSignalModes),
      contract("Oscilloscope", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Oscilloscope"),
        { ...defaultsFor("Oscilloscope"), ...runtimeOptions(), _frameIndex: 0 },
        {
          ...defaultsFor("Oscilloscope"),
          ...runtimeOptions(),
          display: "INVALID",
          phosphor: "INVALID",
          beamWidth: Number.NaN,
          intensity: Number.POSITIVE_INFINITY,
          bloom: Number.NaN,
          bloomStrength: Number.NEGATIVE_INFINITY,
          persistence: Number.NaN,
          graticuleDivs: Number.NaN,
          noiseFloor: Number.NaN,
          _frameIndex: Number.NaN,
        },
        0,
      )),
      contract("CCD Charge Smear", "additive-overload-drain-and-direction", runCcdChargeAccumulation),
      contract("CCD Charge Smear", "zero-strength-identity", () => runIdentity(
        filterFor("CCD Charge Smear"),
        {
          ...defaultsFor("CCD Charge Smear"),
          ...runtimeOptions(),
          threshold: 0.5,
          strength: 0,
          antiBlooming: 0,
        },
        0,
      )),
      contract("CCD Charge Smear", "malformed-state-falls-back", () => runEquivalent(
        filterFor("CCD Charge Smear"),
        { ...defaultsFor("CCD Charge Smear"), ...runtimeOptions() },
        {
          ...defaultsFor("CCD Charge Smear"),
          ...runtimeOptions(),
          threshold: Number.NaN,
          strength: Number.POSITIVE_INFINITY,
          length: Number.NaN,
          decay: Number.NaN,
          direction: "INVALID",
          antiBlooming: Number.NaN,
        },
        0,
      )),
      contract("Laser Speckle Projector", "diversity-contrast-and-mean", runLaserSpeckleDiversity),
      contract("Laser Speckle Projector", "zero-coherence-identity", () => runIdentity(
        filterFor("Laser Speckle Projector"),
        {
          ...defaultsFor("Laser Speckle Projector"),
          ...runtimeOptions(),
          _frameIndex: 0,
          coherence: 0,
          scanStrength: 0,
          bloom: 0,
        },
        1,
      )),
      contract("Laser Speckle Projector", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Laser Speckle Projector"),
        { ...defaultsFor("Laser Speckle Projector"), ...runtimeOptions(), _frameIndex: 0 },
        {
          ...defaultsFor("Laser Speckle Projector"),
          ...runtimeOptions(),
          laser: "INVALID",
          grain: Number.NaN,
          coherence: Number.POSITIVE_INFINITY,
          diversity: Number.NaN,
          scanPitch: Number.NaN,
          scanStrength: Number.NaN,
          bloom: Number.NaN,
          motion: Number.NaN,
          _frameIndex: Number.NaN,
        },
        0,
      )),
    ],
  },
  {
    name: "consumer-imaging",
    contracts: [
      contract("E-ink", "display-levels-cells-refresh-and-parity", runEinkDisplayContracts),
      contract("E-ink", "malformed-state-falls-back", () => runEquivalent(
        filterFor("E-ink"),
        {
          ...defaultsFor("E-ink"),
          ...runtimeOptions(),
          _isAnimating: false,
          _prevOutput: null,
        },
        {
          ...defaultsFor("E-ink"),
          ...runtimeOptions(),
          mode: "INVALID",
          refreshMode: "INVALID",
          contrast: Number.NaN,
          paperWhite: Number.POSITIVE_INFINITY,
          inkBlack: Number.NEGATIVE_INFINITY,
          colorSaturation: Number.NaN,
          ghosting: Number.NaN,
          texture: Number.NaN,
          fullRefreshEvery: Number.NaN,
          pixelGrid: "false",
          _frameIndex: Number.NaN,
          _isAnimating: false,
          _prevOutput: null,
        },
        0,
      )),
      contract("Vintage TV", "signal-bandwidth-roll-and-raster", runVintageTvSignalContracts),
      contract("Vintage TV", "zero-impairments-identity", () => runIdentity(
        filterFor("Vintage TV"),
        {
          ...defaultsFor("Vintage TV"),
          ...runtimeOptions(),
          palette: identityPalette,
          banding: 0,
          colorFringe: 0,
          chromaBandwidth: 0,
          tuningError: 0,
          verticalRoll: 0,
          scanlineStrength: 0,
          glow: 0,
          rfNoise: 0,
        },
        2,
      )),
      contract("Vintage TV", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Vintage TV"),
        { ...defaultsFor("Vintage TV"), ...runtimeOptions(), _frameIndex: 0 },
        {
          ...defaultsFor("Vintage TV"),
          ...runtimeOptions(),
          system: "INVALID",
          banding: Number.NaN,
          colorFringe: Number.POSITIVE_INFINITY,
          chromaBandwidth: Number.NaN,
          tuningError: Number.NEGATIVE_INFINITY,
          verticalRoll: Number.NaN,
          scanlineStrength: Number.NaN,
          glow: Number.NaN,
          rfNoise: Number.NaN,
          _frameIndex: Number.NaN,
        },
        0,
      )),
      contract("Digicam Flash", "linear-exposure-and-cpu-gl-parity", runDigicamFlashContracts),
      contract("Digicam Flash", "zero-flash-identity", () => runIdentity(
        filterFor("Digicam Flash"),
        {
          ...defaultsFor("Digicam Flash"),
          ...runtimeOptions(),
          palette: identityPalette,
          flashPower: 0,
          ambient: 1,
          edgeBurn: 0,
          whiteClip: 255,
          warmth: 0,
        },
        1,
      )),
      contract("Digicam Flash", "malformed-state-falls-back", () => runEquivalent(
        filterFor("Digicam Flash"),
        { ...defaultsFor("Digicam Flash"), ...runtimeOptions() },
        {
          ...defaultsFor("Digicam Flash"),
          ...runtimeOptions(),
          flashPower: Number.NaN,
          falloff: Number.POSITIVE_INFINITY,
          centerX: Number.NaN,
          centerY: Number.NEGATIVE_INFINITY,
          ambient: Number.NaN,
          edgeBurn: Number.NaN,
          whiteClip: Number.NaN,
          warmth: Number.NaN,
        },
        0,
      )),
    ],
  },
  {
    name: "physical-media",
    contracts: [
      ...(["Newspaper", "Polaroid", "Thermal Printer"] as const).map((name) =>
        contract(name, "fixed-medium-frame-invariance", () => runStaticArtifactFrameInvariance(name))),
      contract("Thermal Printer", "print-head-cell-coherence", runThermalPrinterCellCoherence),
      contract("Polaroid", "no-forced-spatial-blur", runPolaroidNoForcedBlur),
      contract("Polaroid", "neutral-grade-identity", () => runIdentity(
        filterFor("Polaroid"),
        {
          ...defaultsFor("Polaroid"),
          ...runtimeOptions(),
          warmth: 0,
          fadedBlacks: 0,
          saturation: 1,
          grain: 0,
          vignette: 0,
        },
        1,
      )),
      contract("Film Grain", "continuous-density-clusters", runFilmGrainContinuousClusters),
      contract("Light Leak", "neutral-spectrum", runLightLeakNeutrality),
      contract("Projection film", "dust-occlusion", runProjectionDustOcclusion),
      contract("Projection film", "scratch-layer-diversity", runProjectionScratchDiversity),
      contract("Photocopier", "fixed-sheet-frame-invariance", runPhotocopierFrameInvariance),
      contract("Photocopier", "continuous-generation-tone", runPhotocopierToneContinuity),
      contract("Paper Texture", "antialiased-high-scale-weave", runPaperTextureHighScaleBounded),
      contract("Sumi-e", "correlated-washi-fibres", runSumiFiberCorrelation),
      contract("Risograph", "fixed-master-frame-invariance", () => runFixedLayeredPrintFrameInvariance("Risograph")),
      contract("Risograph (multi-layer)", "fixed-master-frame-invariance", () => runFixedLayeredPrintFrameInvariance("Risograph (multi-layer)")),
      contract("Risograph", "zero-bleed-no-forced-blur", runRisographNoForcedBleed),
      contract("Duplex Print", "paper-highlights", runDuplexPaperHighlights),
      contract("Screen Print", "clustered-dot-paper-coverage", runScreenPrintHalftone),
      contract("Infrared", "neutral-reflectance", runInfraredNeutrality),
      contract("Nokia LCD", "two-state-grid", runNokiaLcdStates),
      contract("Daguerreotype", "view-angle-reflection", runDaguerreotypeViewAngle),
      contract("Film Burn", "zero-hotspot-identity", () => runIdentity(
        filterFor("Film Burn"),
        { ...defaultsFor("Film Burn"), ...runtimeOptions(), hotspots: 0 },
        0,
      )),
      contract("Ink Bleed", "fiber-axis-equivalence", () => runEquivalent(
        filterFor("Ink Bleed"),
        { ...defaultsFor("Ink Bleed"), ...runtimeOptions(), fiberAngle: 0 },
        { ...defaultsFor("Ink Bleed"), ...runtimeOptions(), fiberAngle: 180 },
        0,
      )),
      contract("Thermal camera", "temporal-noise", runThermalNoiseContract),
    ],
  },
  {
    name: "printmaking-stylizers",
    contracts: [
      contract("printmaking stylizers", "tone-density-monotonic", runPrintmakingToneMonotonic),
      contract("Stipple", "density-not-size-modulation", runStippleDensityModulation),
      contract("printmaking stylizers", "source-alpha-preservation", runPrintmakingAlphaPreservation),
    ],
  },
  {
    name: "optical-convolution",
    contracts: [
      contract("Despeckle", "impulse-removal", runDespeckleImpulseRemoval),
      contract("Despeckle", "edge-preserved", runDespeckleEdgePreserved),
      contract("Sharpen", "gaussian-unsharp-overshoot", runSharpenEdgeContrast),
      contract("Bloom", "linear-multiscale-glow", runBloomLinearGlow),
      contract("Bokeh", "highlight-disc-spread", runBokehHighlightSpread),
      contract("Frequency Filter", "gaussian-lowpass-not-box", runFrequencyGaussianLowpass),
    ],
  },
  {
    name: "glitch-codec",
    contracts: [
      contract("Analog Static", "multipath-ghost-and-alpha", runAnalogStaticGhostAndAlpha),
    ],
  },
  {
    name: "simulation",
    contracts: [
      contract("Stable Fluids", "projection-finite-and-live", runStableFluidsProjectionStable),
      contract("Stable Fluids", "no-projection-renders", runStableFluidsNoProjectionRenders),
      contract("Wake Turbulence", "motion-gated-warp", runWakeMotionGated),
    ],
  },
  {
    name: "tone-and-light",
    contracts: [
      contract("Solarize", "sabattier-reversal", runSolarizeReversal),
      contract("Atmospheric Haze", "koschmieder-depth-airlight", runHazeKoschmiederDepth),
      contract("Dodge / Burn", "linear-exposure-directional", runDodgeBurnDirectional),
    ],
  },
  {
    name: "warp-and-print",
    contracts: [
      contract("Anamorphic Cylinder", "linear-reflection-radial", runAnamorphicLinearRadial),
      contract("Stamp", "edge-concentrated-breakup", runStampEdgeBreakup),
      contract("Wallpaper Tiling", "p2-rotation-not-mirror", runWallpaperP2Rotation),
      contract("Contour Map", "iso-contour-lines", runContourIsoLines),
    ],
  },
  {
    name: "linear-light-accumulation",
    contracts: [
      contract("Motion Blur", "linear-streak-average", runMotionBlurLinearStreak),
      contract("Radial Blur", "linear-radial-average", runRadialBlurLinearAverage),
      contract("Long Exposure", "linear-shutter-accumulation", runLongExposureLinearAccumulation),
      contract("Halation", "linear-screen-diffusion", runHalationLinearScreen),
      contract("Orton", "linear-screen-glow", runOrtonLinearGlow),
      contract("Tilt Shift", "linear-defocus-psf", runTiltShiftLinearDefocus),
      contract("Volumetric Light", "linear-shaft-integration", runVolumetricLightLinearShafts),
      contract("CCD Charge Smear", "linear-well-overflow-bloom", runCcdChargeLinearBloom),
    ],
  },
  {
    name: "alpha-preservation",
    contracts: [
      contract("Color Cycle", "hue-rotate-keeps-alpha", runTemporalColorCycleAlphaPreserved),
      contract("Scanline Warp", "alpha-warped-not-opaque", runScanlineWarpAlphaWarped),
      contract("Color Gradient Noise", "blend-keeps-alpha", runColorGradientNoiseAlphaPreserved),
    ],
  },
  {
    name: "harness",
    contracts: [
      contract("harness", "shared-runtime-fixture-integrity", runtimeFixtureIntegrity),
      contract("canvas ownership", "allocation-plateau-and-readout-reuse", runCanvasOwnershipReuse),
    ],
  },
];
