// @flow

export const LOAD_IMAGE = "LOAD_IMAGE";
export const LOAD_STATE = "LOAD_STATE";
export const FILTER_IMAGE = "FILTER_IMAGE";
export const SELECT_FILTER = "SELECT_FILTER";
export const SET_FILTER_OPTION = "SET_FILTER_OPTION";
export const SET_FILTER_PALETTE_OPTION = "SET_FILTER_PALETTE_OPTION";
export const ADD_PALETTE_COLOR = "ADD_PALETTE_COLOR";
export const SAVE_CURRENT_COLOR_PALETTE = "SAVE_CURRENT_COLOR_PALETTE";
export const DELETE_CURRENT_COLOR_PALETTE = "DELETE_CURRENT_COLOR_PALETTE";
export const SET_GRAYSCALE = "SET_GRAYSCALE";
export const SET_SCALE = "SET_SCALE";
export const SET_OUTPUT_SCALE = "SET_OUTPUT_SCALE";
export const SET_REAL_TIME_FILTERING = "SET_REAL_TIME_FILTERING";
export const SET_INPUT_CANVAS = "SET_INPUT_CANVAS";
export const SET_INPUT_VOLUME = "SET_INPUT_VOLUME";
export const SET_INPUT_PLAYBACK_RATE = "SET_INPUT_PLAYBACK_RATE";
export const SET_SCALING_ALGORITHM = "SET_SCALING_ALGORITHM";
export const ERROR = "ERROR";

export const ASYNC_FILTER = "ASYNC_FILTER";
