// @flow

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const LOAD_IMAGE = "LOAD_IMAGE";
export const FILTER_IMAGE = "FILTER_IMAGE";
export const SELECT_FILTER = "SELECT_FILTER";
export const SET_FILTER_OPTION = "SET_FILTER_OPTION";
export const SET_FILTER_PALETTE_OPTION = "SET_FILTER_PALETTE_OPTION";
export const ADD_PALETTE_COLOR = "ADD_PALETTE_COLOR";
export const SAVE_CURRENT_COLOR_PALETTE = "SAVE_CURRENT_COLOR_PALETTE";
export const SET_GRAYSCALE = "SET_GRAYSCALE";
export const SET_SCALE = "SET_SCALE";
export const ERROR = "ERROR";
