export const RGB_NEAREST = "RGB_NEAREST_FAST";
export const RGB_APPROX = "RGB_APPROX";
export const HSV_NEAREST = "HSV_NEAREST";
export const LAB_NEAREST = "JS_LAB_NEAREST_BEST";
export const WASM_LAB_NEAREST = "WASM_LAB_NEAREST_BEST";
export const WASM_LAB_NEAREST_MEMO_PALETTE = "WASM_LAB_NEAREST_MEMO_PALETTE";
